# -*- coding: utf-8 -*-
""".ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fGFDYLTx8raKCnNJgPwH9JGLIBOE81m1
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

notas = pd.read_csv('ratings.csv')
notas

notas.shape

notas.columns = ['usuarioID', 'filmeID', 'nota', 'momento']

notas['nota'].unique()

notas['nota'].value_counts()

notas['nota'].mean()

notas['nota'].plot(kind='hist')

notas['nota'].median()

mediana = notas['nota'].median()
media = notas['nota'].mean()
print(f'Mediana é {mediana}')
print(f'Média é {media}')

notas['nota'].describe()

sns.boxplot(notas['nota'])

filmes = pd.read_csv('movies.csv')
filmes.columns = ['filmeId', 'titulo', 'generos']
filmes.head()

notas.query('filmeID==1')['nota'].mean()

notas.query('filmeID==2')['nota'].mean()

medias_por_filme = notas.groupby('filmeID')['nota'].mean()
medias_por_filme.head()

medias_por_filme.plot(kind='hist')

sns.boxplot(medias_por_filme)

medias_por_filme.describe()

sns.distplot(medias_por_filme, kde=True)
plt.title('Histograma das médias dos filmes')